/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import negocio.Encuesta;
import negocio.GestorEncuestas;

/**
 *
 * @author Aldo
 */
public class VentanaNvaEncuesta extends javax.swing.JFrame {

    private GestorEncuestas gestor;
    private VentanaPpal ppal;
    ArrayList<Encuesta> encuesta;
    String[] carreras;

    int cod;

    /**
     * Creates new form VentanaNvaEncuesta
     */
    public VentanaNvaEncuesta(VentanaPpal vp, GestorEncuestas g) {
        initComponents();
        ppal = vp;
        gestor = g;
        this.encuesta = new ArrayList<Encuesta>();
        carreras=new String[4];
        txtCodigo.setText(String.valueOf(Encuesta.getNro()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrupGenero = new javax.swing.ButtonGroup();
        txtEdad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        rbFemenino = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        chkMedicina = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        chkArquitectura = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        chkIngenieria = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        chkOtras = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        cmbNivelEducacion = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        bgrupGenero.add(rbMasculino);
        rbMasculino.setText("Masculino");

        jLabel2.setText("Apellido: ");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        bgrupGenero.add(rbFemenino);
        rbFemenino.setText("Femenino");

        jLabel3.setText("Nombre:");

        chkMedicina.setText("Medicina");

        jLabel4.setText("Edad:");

        chkArquitectura.setText("Arquitectura");

        jLabel5.setText("Genero: ");

        chkIngenieria.setText("Ingeniaría");

        jLabel6.setText("Carreras que estudió:");

        chkOtras.setText("Otras");

        jLabel7.setText("Nivel de educación alcanzado:");

        cmbNivelEducacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Item", "Ninguno", "Inicial", "Primario", "Secundario", "Terciario", "Universitario", "Posgrado" }));

        txtCodigo.setEditable(false);

        jLabel8.setText("NUEVA ENCUESTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellido)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkMedicina)
                                    .addComponent(chkArquitectura))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkOtras)
                                    .addComponent(chkIngenieria)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbFemenino)
                                    .addComponent(rbMasculino)))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(28, 28, 28)
                                .addComponent(cmbNivelEducacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(30, 30, 30)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(78, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbMasculino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFemenino)
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMedicina)
                    .addComponent(chkIngenieria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkArquitectura)
                    .addComponent(chkOtras))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbNivelEducacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalir))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        ppal.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (Validar()) {
            if (encuesta.isEmpty()) {
                cod = 1;
                txtCodigo.setText(String.valueOf(cod));
            } else {

                cod = encuesta.lastIndexOf(gestor);
                txtCodigo.setText(String.valueOf(encuesta.get(cod).getCodigo()));
            }

            String apellido = txtApellido.getText();
            String nombre = txtNombre.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            char genero = 'M';
            if (rbFemenino.isSelected()) {
                genero = 'F';
            }
            if (chkMedicina.isSelected()) {
                carreras[0]="Medicina";
            }
            if (chkArquitectura.isSelected()) {
                carreras[1]="Arquitectura";
            }
            if (chkIngenieria.isSelected()) {
                carreras[2]="Ingeniría";
            }
            if (chkOtras.isSelected()) {
                carreras[3]="Otras";
            }

            int nivelducativo = cmbNivelEducacion.getSelectedIndex();
            Encuesta e = new Encuesta(apellido, nombre, edad, genero,carreras, nivelducativo);
            
            gestor.addencuesta(e);
            JOptionPane.showMessageDialog(this, "La encuesta se grabó con exito");
            txtCodigo.setText(String.valueOf(e.getCodigo()));
            Limpiar();

        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    private boolean Validar() {
        boolean res = true;

        if (txtApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el apellido");
            //           res = false;
            txtApellido.requestFocus();
        } else if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre");
//            res = false;
            txtNombre.requestFocus();
        } else if (txtEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la edad");
//            res = false;
            txtEdad.requestFocus();
        } else if (!txtEdad.getText().isEmpty()) {
            int a = 0;
            try {
                a = Integer.parseInt(txtEdad.getText());
            } catch (java.lang.NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Debe Ingresar un nro entero");
//                res = false;
                txtEdad.setText("");
                txtEdad.requestFocus();
            }

        }
        if (!rbMasculino.isSelected() && !rbFemenino.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debe igresar el genenro");
//            res = false;
            rbMasculino.requestFocus();
        } else if (cmbNivelEducacion.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debe elegir nivel educativo");
//            res = false;
            cmbNivelEducacion.requestFocus();
        }
        return res;
    }

    private void Limpiar() {
        txtApellido.setText("");
        txtNombre.setText("");
        txtEdad.setText("");
        bgrupGenero.clearSelection();
        chkArquitectura.setSelected(false);
        chkIngenieria.setSelected(false);
        chkMedicina.setSelected(false);
        chkOtras.setSelected(false);
        cmbNivelEducacion.setSelectedIndex(0);
        for (int i = 0; i < carreras.length; i++) {
            carreras[i]="";
        }
        txtApellido.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrupGenero;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkArquitectura;
    private javax.swing.JCheckBox chkIngenieria;
    private javax.swing.JCheckBox chkMedicina;
    private javax.swing.JCheckBox chkOtras;
    private javax.swing.JComboBox<String> cmbNivelEducacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
