/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import negocio.GestorEncuestas;

/**
 *
 * @author Aldo
 */
public class VentanaPpal extends javax.swing.JFrame {
    GestorEncuestas gestor;
    /**
     * Creates new form VentanaPpal
     */
    public VentanaPpal() {
        initComponents();
        gestor=new GestorEncuestas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        barra = new javax.swing.JMenuBar();
        mnuEncuestas = new javax.swing.JMenu();
        mnuItemEncuestaNuevo = new javax.swing.JMenuItem();
        mnuItemEncuestasModificar = new javax.swing.JMenuItem();
        mnuItemEncuestaEliminar = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mnuItemReportesPromedio = new javax.swing.JMenuItem();
        mnuItemReportesListados = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mnuItemSalirSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuEncuestas.setText("Encuestas");

        mnuItemEncuestaNuevo.setText("Nuevo");
        mnuItemEncuestaNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemEncuestaNuevoActionPerformed(evt);
            }
        });
        mnuEncuestas.add(mnuItemEncuestaNuevo);

        mnuItemEncuestasModificar.setText("Modificar");
        mnuEncuestas.add(mnuItemEncuestasModificar);

        mnuItemEncuestaEliminar.setText("Eliminar");
        mnuEncuestas.add(mnuItemEncuestaEliminar);

        barra.add(mnuEncuestas);

        mnuReportes.setText("Reportes");

        mnuItemReportesPromedio.setText("Edad Promedio");
        mnuItemReportesPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemReportesPromedioActionPerformed(evt);
            }
        });
        mnuReportes.add(mnuItemReportesPromedio);

        mnuItemReportesListados.setText("Listados Ordenados");
        mnuItemReportesListados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemReportesListadosActionPerformed(evt);
            }
        });
        mnuReportes.add(mnuItemReportesListados);

        barra.add(mnuReportes);

        mnuSalir.setText("Salir");

        mnuItemSalirSalir.setText("Salir");
        mnuItemSalirSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSalirSalirActionPerformed(evt);
            }
        });
        mnuSalir.add(mnuItemSalirSalir);

        barra.add(mnuSalir);

        setJMenuBar(barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemSalirSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSalirSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuItemSalirSalirActionPerformed

    private void mnuItemReportesListadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemReportesListadosActionPerformed
        // TODO add your handling code here:
        VentanaListadosOrdenados vlo=new VentanaListadosOrdenados(this,gestor);
        vlo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItemReportesListadosActionPerformed

    private void mnuItemEncuestaNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemEncuestaNuevoActionPerformed
        // TODO add your handling code here:
        VentanaNvaEncuesta vne=new VentanaNvaEncuesta(this,gestor);
        vne.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItemEncuestaNuevoActionPerformed

    private void mnuItemReportesPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemReportesPromedioActionPerformed
        // TODO add your handling code here:
        VentanaPromedioEdad vpe=new VentanaPromedioEdad(this, gestor);
        vpe.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_mnuItemReportesPromedioActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barra;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnuEncuestas;
    private javax.swing.JMenuItem mnuItemEncuestaEliminar;
    private javax.swing.JMenuItem mnuItemEncuestaNuevo;
    private javax.swing.JMenuItem mnuItemEncuestasModificar;
    private javax.swing.JMenuItem mnuItemReportesListados;
    private javax.swing.JMenuItem mnuItemReportesPromedio;
    private javax.swing.JMenuItem mnuItemSalirSalir;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
